# Generated by Django 3.1.2 on 2020-12-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffData',
            fields=[
                ('staff_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fullname', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=10, null=True)),
                ('alternate_number', models.CharField(blank=True, max_length=10, null=True)),
                ('dob', models.CharField(blank=True, max_length=10, null=True)),
                ('aadhar_number', models.IntegerField(blank=True)),
            ],
            options={
                'db_table': 'StaffData',
            },
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('created_date', models.DateTimeField(auto_now=True)),
                ('updated_record_date', models.CharField(default='Not Availiable', max_length=100)),
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('role_id', models.CharField(default='1', max_length=5)),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('status', models.CharField(default='1', max_length=5)),
            ],
            options={
                'db_table': 'UserData',
            },
        ),
        migrations.CreateModel(
            name='VehiclesData',
            fields=[
                ('vehicle_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=50)),
                ('vehicle_name', models.CharField(max_length=100)),
                ('number_plate', models.CharField(max_length=100)),
                ('rc_number', models.CharField(max_length=50)),
                ('vehicle_insurance', models.CharField(max_length=50)),
                ('manufacture_date', models.CharField(max_length=20)),
                ('puc', models.CharField(max_length=100)),
                ('status', models.CharField(default='1', max_length=5)),
            ],
            options={
                'db_table': 'VehiclesData',
            },
        ),
    ]
