# Generated by Django 3.1.2 on 2020-12-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclesdata',
            name='driver_id',
            field=models.CharField(default='Not Assigned', max_length=100),
        ),
    ]
