# Generated by Django 3.1.2 on 2020-12-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_vehiclesdata_driver_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffdata',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='staffdata',
            name='staff_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staffdata',
            name='user_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staffdata',
            name='dob',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='staffdata',
            name='username',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
