# Generated by Django 3.1.2 on 2020-12-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201224_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclesdata',
            name='driver_id',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
