# Generated by Django 3.1.1 on 2020-12-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201224_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessData',
            fields=[
                ('business_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'BusinessData',
            },
        ),
        migrations.CreateModel(
            name='StaffTypeData',
            fields=[
                ('staff_type_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('staff_type_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'StaffTypeData',
            },
        ),
    ]
