# Generated by Django 3.1.1 on 2020-12-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_businessdata_stafftypedata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffdata',
            old_name='user_id',
            new_name='business_id',
        ),
        migrations.RemoveField(
            model_name='staffdata',
            name='aadhar_number',
        ),
        migrations.RemoveField(
            model_name='staffdata',
            name='alternate_number',
        ),
        migrations.RemoveField(
            model_name='staffdata',
            name='staff_name',
        ),
        migrations.AddField(
            model_name='staffdata',
            name='aadhar',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffdata',
            name='alternate_mobile',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffdata',
            name='driving_license',
            field=models.FileField(default=1, upload_to='drivinglicense/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffdata',
            name='mobile',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffdata',
            name='password',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffdata',
            name='profile_picture',
            field=models.FileField(default=1, upload_to='staffprofilepicture/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffdata',
            name='staff_type_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffdata',
            name='status',
            field=models.CharField(default='1', max_length=5),
        ),
        migrations.AlterField(
            model_name='staffdata',
            name='dob',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staffdata',
            name='fullname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staffdata',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
