# Generated by Django 3.1.1 on 2020-12-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201228_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclesdata',
            name='vehicle_photo',
            field=models.FileField(default='Not Availiable', upload_to='vehicles/'),
        ),
    ]
