# Generated by Django 3.1.1 on 2020-12-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_vehiclesdata_driver_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CylinderBillData',
            fields=[
                ('created_date', models.DateTimeField(auto_now=True)),
                ('bill_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('business_id', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=50)),
                ('empty_cylinder_returned', models.CharField(max_length=50)),
                ('paymode', models.CharField(default='1', max_length=5)),
                ('total_price', models.CharField(max_length=50)),
                ('bill_date', models.CharField(max_length=50)),
                ('bill', models.FileField(default='Not Availiable', upload_to='cylinderbills/')),
            ],
            options={
                'db_table': 'CylinderBillData',
            },
        ),
    ]
