# Generated by Django 3.1.1 on 2020-12-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_cylinderbilldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='CylinderAssignData',
            fields=[
                ('created_date', models.DateTimeField(auto_now=True)),
                ('assign_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('vehicle_id', models.CharField(max_length=50)),
                ('staff_id', models.CharField(max_length=50)),
                ('business_id', models.CharField(max_length=50)),
                ('filled_quantity', models.CharField(max_length=50)),
                ('current_cylinder_cost', models.CharField(max_length=50)),
                ('assign_date', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'CylinderAssignData',
            },
        ),
        migrations.AddField(
            model_name='vehiclesdata',
            name='assign_id',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
