# Generated by Django 3.1.2 on 2020-12-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20201229_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclesdata',
            name='insurence_number',
            field=models.FileField(default='Not Availiable', upload_to='vehicle_insurence/'),
        ),
        migrations.AlterField(
            model_name='vehiclesdata',
            name='puc',
            field=models.FileField(default='Not Availiable', upload_to='vehicle_puc/'),
        ),
        migrations.AlterField(
            model_name='vehiclesdata',
            name='rc_number',
            field=models.FileField(default='Not Availiable', upload_to='vehicle_rc/'),
        ),
    ]
