# Generated by Django 3.1.1 on 2021-01-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20201230_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdata',
            name='business_picture',
            field=models.FileField(default='NA', upload_to='businesspic/'),
        ),
    ]
