# Generated by Django 3.1.1 on 2021-01-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_businessdata_business_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafftypedata',
            name='role_id',
            field=models.CharField(default='NA', max_length=10),
        ),
    ]
