# Generated by Django 3.1.1 on 2021-01-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_stafftypedata_role_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminData',
            fields=[
                ('created_date', models.DateTimeField(auto_now=True)),
                ('admin_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('status', models.CharField(default='1', max_length=5)),
            ],
            options={
                'db_table': 'AdminData',
            },
        ),
    ]
