# Generated by Django 3.1.1 on 2021-01-06 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_admindata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
