# Generated by Django 3.1.1 on 2021-01-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_delete_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='admindata',
            name='mobile',
            field=models.CharField(default='NA', max_length=15),
        ),
    ]
