# Generated by Django 3.1.1 on 2021-01-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_admindata_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DieselBillData',
            fields=[
                ('created_date', models.DateTimeField(auto_now=True)),
                ('bill_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('business_id', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=50)),
                ('price_per_liter', models.CharField(max_length=50)),
                ('total_price', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'DieselBillData',
            },
        ),
        migrations.CreateModel(
            name='PatrolBillData',
            fields=[
                ('created_date', models.DateTimeField(auto_now=True)),
                ('bill_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('business_id', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=50)),
                ('price_per_liter', models.CharField(max_length=50)),
                ('total_price', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'PatrolBillData',
            },
        ),
    ]
