# Generated by Django 3.1.1 on 2021-01-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20210112_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetrolBillData',
            fields=[
                ('bill_date', models.CharField(max_length=50)),
                ('bill_time', models.CharField(max_length=50)),
                ('bill_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('business_id', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=50)),
                ('price_per_liter', models.CharField(max_length=50)),
                ('total_price', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'PetrolBillData',
            },
        ),
        migrations.DeleteModel(
            name='PatrolBillData',
        ),
        migrations.AddField(
            model_name='dieselbilldata',
            name='bill_time',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dieselbilldata',
            name='bill_date',
            field=models.CharField(max_length=50),
        ),
    ]
