# Generated by Django 3.1.1 on 2021-01-13 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20210112_1652'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CylinderBillData',
            new_name='CylinderPurchaseData',
        ),
        migrations.AlterModelTable(
            name='cylinderpurchasedata',
            table='CylinderPurchaseData',
        ),
    ]
