# Generated by Django 3.1.1 on 2021-01-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20210113_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='CylinderData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('business_id', models.CharField(max_length=50)),
                ('total_filled_cylinder', models.CharField(max_length=50)),
                ('total_empty_cylinder', models.CharField(max_length=50)),
                ('total_cylinder', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'CylinderData',
            },
        ),
        migrations.RenameField(
            model_name='cylinderpurchasedata',
            old_name='empty_cylinder_returned',
            new_name='empty_cylinder_sent',
        ),
    ]
