# Generated by Django 3.1.1 on 2021-01-15 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20210114_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cylinderdata',
            name='total_cylinder',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='cylinderdata',
            name='total_empty_cylinder',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='cylinderdata',
            name='total_filled_cylinder',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
