# Generated by Django 3.1.1 on 2021-01-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20210115_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='CylinderDailyReportData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('business_id', models.CharField(max_length=50)),
                ('entry_date', models.CharField(max_length=50)),
                ('total_cylinder_sold', models.CharField(max_length=50)),
                ('per_cylinder_cost', models.CharField(max_length=50)),
                ('profit', models.CharField(max_length=50)),
                ('total_filled_cylinder_left', models.CharField(max_length=50)),
                ('total_empty_cylinder_left', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'CylinderDailyReportData',
            },
        ),
    ]
