# Generated by Django 3.1.1 on 2021-01-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_cylinderdailyreportdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cylinderdailyreportdata',
            old_name='total_cylinder_sold',
            new_name='total_empty_cylinder',
        ),
        migrations.RenameField(
            model_name='cylinderdailyreportdata',
            old_name='total_empty_cylinder_left',
            new_name='total_filled_cylinder',
        ),
        migrations.RemoveField(
            model_name='cylinderdailyreportdata',
            name='total_filled_cylinder_left',
        ),
        migrations.AddField(
            model_name='cylinderpurchasedata',
            name='per_cylinder_price',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='cylinderpurchasedata',
            name='slot_quantity',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
