# Generated by Django 3.1.1 on 2021-01-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20210115_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='cylinderassigndata',
            name='bill_id',
            field=models.CharField(default='NA', max_length=50),
        ),
    ]
