# Generated by Django 3.1.1 on 2021-01-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_cylinderassigndata_bill_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CylinderAssignData2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now=True)),
                ('assign_id', models.CharField(max_length=50)),
                ('bill_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'CylinderAssignData2',
            },
        ),
        migrations.RemoveField(
            model_name='cylinderassigndata',
            name='bill_id',
        ),
        migrations.RemoveField(
            model_name='cylinderdailyreportdata',
            name='id',
        ),
        migrations.AddField(
            model_name='cylinderdailyreportdata',
            name='report_id',
            field=models.CharField(default=1, max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
