# Generated by Django 3.1.1 on 2021-01-16 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20210116_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cylinderdailyreportdata',
            old_name='total_empty_cylinder',
            new_name='total_empty_cylinder_returned',
        ),
        migrations.RenameField(
            model_name='cylinderdailyreportdata',
            old_name='total_filled_cylinder',
            new_name='total_filled_cylinder_returned',
        ),
    ]
