# Generated by Django 3.1.1 on 2021-01-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20210116_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='cylinderassigndata2',
            name='business_id',
            field=models.CharField(default='B001', max_length=50),
        ),
    ]
