# Generated by Django 3.1.1 on 2021-01-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_cylinderassigndata2_business_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cylinderassigndata',
            name='completed',
            field=models.CharField(default='0', max_length=4),
        ),
    ]
