# Generated by Django 3.1.1 on 2021-01-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_cylinderassigndata_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='cylinderassigndata',
            name='empty_quantity_returned',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='cylinderassigndata',
            name='filled_quantity_returned',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='cylinderassigndata',
            name='report_generated',
            field=models.CharField(default='0', max_length=4),
        ),
        migrations.AddField(
            model_name='cylinderdailyreportdata',
            name='total_cylinder_assigned',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cylinderdailyreportdata',
            name='total_cylinder_sold',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
