# Generated by Django 3.1.1 on 2021-02-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20210118_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='DieselPurchaseData',
            fields=[
                ('created_date', models.DateTimeField(auto_now=True)),
                ('bill_date', models.CharField(max_length=50)),
                ('bill_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('business_id', models.CharField(max_length=50)),
                ('purchased_quantity', models.CharField(max_length=50)),
                ('price_per_liter', models.CharField(max_length=50)),
                ('total_price', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'DieselPurchaseData',
            },
        ),
        migrations.CreateModel(
            name='FuelData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('business_id', models.CharField(max_length=50)),
                ('current_petrol_quantity', models.CharField(default='0', max_length=50)),
                ('current_diesel_quantity', models.CharField(default='0', max_length=50)),
            ],
            options={
                'db_table': 'FuelData',
            },
        ),
        migrations.CreateModel(
            name='PetrolPurchaseData',
            fields=[
                ('created_date', models.DateTimeField(auto_now=True)),
                ('bill_date', models.CharField(max_length=50)),
                ('bill_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('business_id', models.CharField(max_length=50)),
                ('purchased_quantity', models.CharField(max_length=50)),
                ('price_per_liter', models.CharField(max_length=50)),
                ('total_price', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'PetrolPurchaseData',
            },
        ),
    ]
