# Generated by Django 3.1.1 on 2021-02-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_dieselpurchasedata_fueldata_petrolpurchasedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelDailyData',
            fields=[
                ('created_date', models.DateTimeField(auto_now=True)),
                ('business_id', models.CharField(max_length=50)),
                ('entry_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('entry_date', models.CharField(max_length=50)),
                ('diesel_profit', models.CharField(max_length=50)),
                ('petrol_profit', models.CharField(max_length=50)),
                ('total_profit', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'FuelDailyData',
            },
        ),
        migrations.AddField(
            model_name='dieselbilldata',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='petrolbilldata',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
