# Generated by Django 3.1.1 on 2021-02-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20210211_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cylinderdata',
            name='total_cylinder',
            field=models.CharField(default='2000', max_length=50),
        ),
        migrations.AlterField(
            model_name='cylinderdata',
            name='total_empty_cylinder',
            field=models.CharField(default='1000', max_length=50),
        ),
        migrations.AlterField(
            model_name='cylinderdata',
            name='total_filled_cylinder',
            field=models.CharField(default='1000', max_length=50),
        ),
    ]
