# Generated by Django 3.1.1 on 2021-04-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_meterreadingdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='DieselBillPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.CharField(max_length=50)),
                ('meter_pic', models.FileField(default='NA', upload_to='dieselsales/')),
            ],
            options={
                'db_table': 'DieselBillPic',
            },
        ),
        migrations.CreateModel(
            name='DieselPurchaseBillsData',
            fields=[
                ('created_date', models.DateTimeField(auto_now=True)),
                ('bill_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('bill', models.FileField(default='NA', upload_to='dieselbills/')),
            ],
            options={
                'db_table': 'DieselPurchaseBillsData',
            },
        ),
        migrations.CreateModel(
            name='PetrolBillPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.CharField(max_length=50)),
                ('meter_pic', models.FileField(default='NA', upload_to='petrolsales/')),
            ],
            options={
                'db_table': 'PetrolBillPic',
            },
        ),
        migrations.CreateModel(
            name='PetrolPurchaseBillsData',
            fields=[
                ('created_date', models.DateTimeField(auto_now=True)),
                ('bill_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('bill', models.FileField(default='NA', upload_to='petrolbills/')),
            ],
            options={
                'db_table': 'PetrolPurchaseBillsData',
            },
        ),
        migrations.AddField(
            model_name='dieselbilldata',
            name='machine_type',
            field=models.CharField(default='machine_1', max_length=50),
        ),
        migrations.AddField(
            model_name='petrolbilldata',
            name='machine_type',
            field=models.CharField(default='machine_1', max_length=50),
        ),
    ]
