# Generated by Django 2.1.1 on 2020-12-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillData',
            fields=[
                ('bill_date', models.DateField(auto_now=True)),
                ('bill_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('customer_id', models.CharField(default='Not Availiable', max_length=50)),
                ('store_id', models.CharField(max_length=50)),
                ('total_amount', models.CharField(default='Not Availiable', max_length=50)),
                ('total_tax_amount', models.CharField(default='Not Availiable', max_length=50)),
                ('total_discount_amount', models.CharField(default='Not Availiable', max_length=50)),
                ('total_amount_to_pay', models.CharField(default='Not Availiable', max_length=50)),
                ('pay_mode', models.CharField(default='Not Availiable', max_length=50)),
                ('transaction_id', models.CharField(default='Not Availiable', max_length=100)),
                ('delete', models.CharField(default='0', max_length=50)),
            ],
            options={
                'db_table': 'BillData',
            },
        ),
        migrations.CreateModel(
            name='BillItemData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.CharField(max_length=50)),
                ('medicine_id', models.CharField(max_length=50)),
                ('store_id', models.CharField(max_length=50)),
                ('quantity', models.CharField(default='Not Availiable', max_length=50)),
                ('amount', models.CharField(default='Not Availiable', max_length=50)),
                ('tax_amount', models.CharField(default='Not Availiable', max_length=50)),
                ('discount_amount', models.CharField(default='Not Availiable', max_length=50)),
                ('amount_to_pay', models.CharField(default='Not Availiable', max_length=50)),
            ],
            options={
                'db_table': 'BillItemData',
            },
        ),
        migrations.CreateModel(
            name='CartData',
            fields=[
                ('cart_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('customer_id', models.CharField(default='Not Availiable', max_length=50)),
                ('store_id', models.CharField(max_length=50)),
                ('total_amount', models.CharField(default='Not Availiable', max_length=50)),
                ('total_tax_amount', models.CharField(default='Not Availiable', max_length=50)),
                ('total_discount_amount', models.CharField(default='Not Availiable', max_length=50)),
                ('total_amount_to_pay', models.CharField(default='Not Availiable', max_length=50)),
            ],
            options={
                'db_table': 'CartData',
            },
        ),
        migrations.CreateModel(
            name='CartItemData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(max_length=50)),
                ('medicine_id', models.CharField(max_length=50)),
                ('store_id', models.CharField(max_length=50)),
                ('quantity', models.CharField(default='Not Availiable', max_length=50)),
                ('amount', models.CharField(default='Not Availiable', max_length=50)),
                ('tax_amount', models.CharField(default='Not Availiable', max_length=50)),
                ('discount_amount', models.CharField(default='Not Availiable', max_length=50)),
                ('amount_to_pay', models.CharField(default='Not Availiable', max_length=50)),
            ],
            options={
                'db_table': 'CartItemData',
            },
        ),
        migrations.CreateModel(
            name='DistributerData',
            fields=[
                ('dist_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('store_id', models.CharField(max_length=50)),
                ('dist_name', models.CharField(default='Not Availiable', max_length=100)),
                ('dist_email', models.CharField(default='Not Availiable', max_length=100)),
                ('dist_mobile', models.CharField(max_length=100)),
                ('dist_sddress', models.CharField(default='Not Availiable', max_length=100)),
                ('dist_gstin', models.CharField(default='Not Availiable', max_length=100)),
                ('dist_balance', models.CharField(default='Not Availiable', max_length=100)),
            ],
            options={
                'db_table': 'DistributerData',
            },
        ),
        migrations.CreateModel(
            name='MedicineData',
            fields=[
                ('created_date', models.DateTimeField(auto_now=True)),
                ('medicine_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('store_id', models.CharField(max_length=50)),
                ('dist_id', models.CharField(default='Not Availiable', max_length=50)),
                ('medicine_name', models.CharField(max_length=100)),
                ('medicine_description', models.CharField(max_length=150)),
                ('medicine_contents', models.CharField(max_length=100)),
                ('medicine_benifits', models.CharField(default='Not Availiable', max_length=100)),
                ('medicine_alternatives', models.CharField(default='Not Availiable', max_length=200)),
                ('medicine_quantity', models.CharField(default='Not Availiable', max_length=10)),
                ('medicine_measuringunit', models.CharField(default='Not Availiable', max_length=10)),
                ('medicine_1stripequals', models.CharField(default='Not Availiable', max_length=10)),
                ('medicine_costprice', models.CharField(default='Not Availiable', max_length=10)),
                ('medicine_sellprice', models.CharField(default='Not Availiable', max_length=10)),
                ('medicine_mrp', models.CharField(default='Not Availiable', max_length=10)),
                ('medicine_fixedrate', models.CharField(default='Not Availiable', max_length=10)),
                ('medicine_discount', models.CharField(default='Not Availiable', max_length=10)),
                ('medicine_gst', models.CharField(default='Not Availiable', max_length=10)),
                ('status', models.CharField(default='0', max_length=50)),
                ('prescription_required', models.CharField(default='0', max_length=50)),
                ('low_stock', models.CharField(default='0', max_length=50)),
                ('contains_expired_stock', models.CharField(default='0', max_length=50)),
            ],
            options={
                'db_table': 'MedicineData',
            },
        ),
        migrations.CreateModel(
            name='MedicineMasterData',
            fields=[
                ('medicine_master_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('medicine_master_name', models.CharField(default='Not Availiable', max_length=100)),
                ('medicine_master_description', models.CharField(default='Not Availiable', max_length=150)),
                ('medicine_master_contents', models.CharField(default='Not Availiable', max_length=100)),
                ('medicine_master_benifits', models.CharField(default='Not Availiable', max_length=100)),
                ('medicine_master_alternatives', models.CharField(default='Not Availiable', max_length=200)),
            ],
            options={
                'db_table': 'MedicineMasterData',
            },
        ),
        migrations.CreateModel(
            name='StoreCustomerData',
            fields=[
                ('customer_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('store_id', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_mobile', models.CharField(max_length=50)),
                ('customer_address', models.CharField(max_length=50)),
                ('customer_doctor', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'StoreCustomerData',
            },
        ),
        migrations.CreateModel(
            name='StoreData',
            fields=[
                ('created_date', models.DateTimeField(auto_now=True)),
                ('store_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=50)),
                ('store_name', models.CharField(default='Not Availiable', max_length=100)),
                ('store_address', models.CharField(default='Not Availiable', max_length=100)),
                ('store_gsttin', models.CharField(default='Not Availiable', max_length=100)),
                ('store_upiid', models.CharField(default='Not Availiable', max_length=100)),
                ('store_bank', models.CharField(default='Not Availiable', max_length=100)),
                ('status', models.CharField(default='1', max_length=100)),
            ],
            options={
                'db_table': 'StoreData',
            },
        ),
        migrations.CreateModel(
            name='StoreLogoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(max_length=50)),
                ('store_logo', models.FileField(upload_to='storelogos/')),
            ],
            options={
                'db_table': 'StoreLogoData',
            },
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('created_date', models.DateTimeField(auto_now=True)),
                ('updated_record_date', models.CharField(default='Not Availiable', max_length=100)),
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('store_id', models.CharField(default='Not Availiable', max_length=50)),
                ('user_email', models.CharField(default='Not Availiable', max_length=100)),
                ('user_mobile', models.CharField(max_length=100)),
                ('user_name', models.CharField(default='Not Availiable', max_length=100)),
                ('status', models.CharField(default='1', max_length=100)),
            ],
            options={
                'db_table': 'UserData',
            },
        ),
    ]
