# Generated by Django 3.1.2 on 2020-12-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distributerdata',
            old_name='dist_sddress',
            new_name='dist_address',
        ),
        migrations.AddField(
            model_name='cartdata',
            name='cart_date',
            field=models.DateField(auto_now=True),
        ),
    ]
