# Generated by Django 2.1.1 on 2021-01-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201223_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineImageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_id', models.CharField(max_length=50)),
                ('medicine_image', models.FileField(upload_to='medicineimages/')),
            ],
            options={
                'db_table': 'MedicineImageData',
            },
        ),
        migrations.AddField(
            model_name='storedata',
            name='store_email',
            field=models.CharField(default='Not Availiable', max_length=100),
        ),
    ]
