# Generated by Django 2.1.1 on 2021-01-08 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210107_1502'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicineData',
        ),
    ]
