# Generated by Django 2.1.1 on 2021-01-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_medicinedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='billdata',
            name='bill_pdf_url',
            field=models.CharField(default='Not Availiable', max_length=100),
        ),
    ]
