# Generated by Django 3.1.5 on 2021-01-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_billdata_bill_pdf_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineBatchData',
            fields=[
                ('created_date', models.DateField(auto_now=True)),
                ('delete_date', models.CharField(default='NA', max_length=50)),
                ('batch_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('medicine_id', models.CharField(max_length=50)),
                ('batch_number', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=50)),
                ('expiry_date', models.CharField(max_length=50)),
                ('status', models.CharField(default='1', max_length=5)),
            ],
            options={
                'db_table': 'MedicineBatchData',
            },
        ),
    ]
