# Generated by Django 3.1.5 on 2021-03-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_billdata_billitemdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubunitData',
            fields=[
                ('subunit_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('subunit_for', models.CharField(max_length=50)),
                ('subunit', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'SubunitData',
            },
        ),
        migrations.CreateModel(
            name='UnitData',
            fields=[
                ('unit_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('unit', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'UnitData',
            },
        ),
    ]
